In [2]:
import numpy as np

In [3]:
array = np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [4]:
array_divididos = np.split(array, 3)
array_divididos

[array([1, 2]), array([3, 4]), array([5, 6])]

In [5]:
for i,value in enumerate(array_divididos):
    print(f"Parte {i+1}->{value}")

Parte 1->[1 2]
Parte 2->[3 4]
Parte 3->[5 6]


In [7]:
temperaturas = np.array([22,21,23,25,20,19,21,
                        24,26,27,25,22,
                        20,18,19,20,21,
                        22,23,24,25,26,
                        27,28,29,30,29,
                        28,27,26,25,24])

temperaturas

array([22, 21, 23, 25, 20, 19, 21, 24, 26, 27, 25, 22, 20, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 29, 28, 27, 26, 25, 24])

In [8]:
semanas = np.split(temperaturas,4)
semanas

[array([22, 21, 23, 25, 20, 19, 21, 24]),
 array([26, 27, 25, 22, 20, 18, 19, 20]),
 array([21, 22, 23, 24, 25, 26, 27, 28]),
 array([29, 30, 29, 28, 27, 26, 25, 24])]

In [9]:
for i, value in enumerate(semanas):
    print(f"Semana{i+1}: {value}")

Semana1: [22 21 23 25 20 19 21 24]
Semana2: [26 27 25 22 20 18 19 20]
Semana3: [21 22 23 24 25 26 27 28]
Semana4: [29 30 29 28 27 26 25 24]


In [10]:
medias_semanas = [np.mean(semana) for semana in semanas]
medias_semanas

[np.float64(21.875), np.float64(22.125), np.float64(24.5), np.float64(27.25)]

In [11]:
for i,value in enumerate(medias_semanas):
    print(f"Média da semana{i+1}: {value:.2f} C")

Média da semana1: 21.88 C
Média da semana2: 22.12 C
Média da semana3: 24.50 C
Média da semana4: 27.25 C
