In [2]:
import numpy as np

In [2]:
array_1d = np.array([1,2,3,4,5])
array_1d.ndim #numero de dimenções
array_1d.shape # Formato do array
print(array_1d.ndim)
print(array_1d.shape)

1
(5,)


In [5]:
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d)
print(array_2d.ndim)
print(array_2d.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [ ]:
array_3d = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
print(array_3d)
print(array_3d.ndim)
print(array_3d.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)


In [18]:
# Acessando por array
# primeiro linha dps coluna
array = array_3d[1,:]
print(array)

IndexError: index 1 is out of bounds for axis 0 with size 1