In [1]:
import numpy as np

In [2]:
array = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
    ])

array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [9]:
fatiamento_linhas = array[0:4, 0:3 ]
fatiamento_linhas

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [11]:
array[1:3, 1:3 ] = [[99,100],[101,102]]
array

array([[  1,   2,   3,   4,   5],
       [  6,  99, 100,   9,  10],
       [ 11, 101, 102,  14,  15],
       [ 16,  17,  18,  19,  20]])