In [2]:
import numpy as np

In [3]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [8]:
soma = np.add(array, 10)
soma

array([11, 12, 13, 14, 15])

In [9]:
subtracao = np.subtract(array,10)
subtracao

array([-9, -8, -7, -6, -5])

In [10]:
produto = np.multiply(array, -2)
produto

array([ -2,  -4,  -6,  -8, -10])

In [11]:
divisao = np.divide(array, 2)
divisao

array([0.5, 1. , 1.5, 2. , 2.5])

In [12]:
#função de trigonometria
seno = np.sin(array)
seno

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [13]:
cosseno = np.cos(array)
cosseno

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [14]:
# funções estatisticas
media = np.mean(array)
media

np.float64(3.0)

In [15]:
desvio_padrao = np.std(array)
desvio_padrao

np.float64(1.4142135623730951)

In [4]:
#7-funçoes de comparação
Comparacao_maior_que_3 = array > 3
Comparacao_maior_que_3


array([False, False, False,  True,  True])

In [ ]:
#8- Combinação de Funçoes
resultado = np.sqrt(array) + np.power(array, 2)
resultado

array([ 2.        ,  5.41421356, 10.73205081, 18.        , 27.23606798])

In [6]:
#9- Funções Exponenciais
exponecial = np.exp(array)
exponecial

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [7]:
logaritimo = np.log(array)
logaritimo

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [8]:
#11 Função de Arredondamento
arredondamento = np.around(array /2)
arredondamento


array([0., 1., 2., 2., 2.])

In [9]:
potencia = np.power(array,3)
potencia

array([  1,   8,  27,  64, 125])