In [2]:
import numpy as np

In [3]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [4]:
novo_array = np.concatenate([array1,array2])
novo_array

array([1, 2, 3, 4, 5, 6])

In [15]:
nomes = np.array(["Alice","Bob","Charrlie"])
notas_matematicas = np.array([85,90,78])
nota_fisica = np.array([88,76,95])

In [16]:
# Usando np.vstack para empilhar verticalmente os dados
dados_estruturados = np.vstack((nomes,notas_matematicas,nota_fisica))
dados_estruturados

array([['Alice', 'Bob', 'Charrlie'],
       ['85', '90', '78'],
       ['88', '76', '95']], dtype='<U21')

In [17]:
# Usando np.hstack para empilhar horizontalmente os dados
matriz_notas = np.column_stack((notas_matematicas,nota_fisica))
matriz_notas

array([[85, 88],
       [90, 76],
       [78, 95]])

In [18]:
# Adicionar uma nova coluna com a média das notas

media_notas = np.mean(matriz_notas, axis=1)
matriz_final = np.column_stack((matriz_notas,media_notas))
matriz_final

array([[85. , 88. , 86.5],
       [90. , 76. , 83. ],
       [78. , 95. , 86.5]])